### ISSUE TITLE
bootstrap-social: logos not visible on all pages

### ISSUE THREAD

**Issue by RamsesNtibu** [ANtibushitse/Front-End-Web-UI-Frameworks-and-Tools--Bootstrap-4#44]
# current _bug_ on (`index.html` `aboutus.html` )

![image](https://user-images.githubusercontent.com/12177787/115318337-8fac8780-a14b-11eb-929c-698af268a606.png)

# excpected _behavior_ (available on `contactus.html`)

![image](https://user-images.githubusercontent.com/12177787/115318467-c8e4f780-a14b-11eb-8b00-074baeeac06b.png)

**Comment by ANtibushitse** [comment]
FIxed
