### ISSUE TITLE
login button: not correctly located on xs-screen on aboutus.html

### ISSUE THREAD

**Issue by RamsesNtibu** [ANtibushitse/Front-End-Web-UI-Frameworks-and-Tools--Bootstrap-4#45]
# current _bug_ on (`aboutus.html` xs-screen)

## xs-screen
![image](https://user-images.githubusercontent.com/12177787/115318695-414bb880-a14c-11eb-9f3f-18e97ca6178b.png)

## sm-screen
![image](https://user-images.githubusercontent.com/12177787/115318754-60e2e100-a14c-11eb-9659-63cc09dbb4d1.png)

# Expected _behavior_

## xs-screen
![image](https://user-images.githubusercontent.com/12177787/115318832-91c31600-a14c-11eb-97f6-89c203f99042.png)

## sm-screen
![image](https://user-images.githubusercontent.com/12177787/115318894-b1f2d500-a14c-11eb-922f-251b83679493.png)

**Comment by ANtibushitse** [comment]
fixed
