### ISSUE TITLE
breadcrumb: not visible on index.html and aboutus.html

### ISSUE THREAD

**Issue by RamsesNtibu** [ANtibushitse/Front-End-Web-UI-Frameworks-and-Tools--Bootstrap-4#46]
# current _bug_

![image](https://user-images.githubusercontent.com/12177787/115318997-df3f8300-a14c-11eb-9a63-db81078cacad.png)

# expected _behavior_

![image](https://user-images.githubusercontent.com/12177787/115319088-05652300-a14d-11eb-9fdf-5f8c89577be1.png)

**Comment by ANtibushitse** [comment]
[](url)
![Screen Shot 2021-04-20 at 12 47 02](https://user-images.githubusercontent.com/20683036/115383904-aa780e00-a1d6-11eb-97bf-84096f389a15.png)
  No breadcrumbs in teacher index.html   🤔

**Comment by RamsesNtibu** [comment]
ok but you need one on aboutus
